import { Inter } from "next/font/google";
import CityBar from "./CityBar";
import Header from "./Header";
import "@/styles/global.css";
import "@/app/globals.css"
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Weather APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Header/>
        </header>
        <CityBar className="flex justify-center" />
        
        {children}

        </body>
    </html>
  );
}
