import { Comic_Neue } from "next/font/google";
import CityBar from "./CityBar";
import Header from "./Header";
import "@/styles/global.css";
import "@/app/globals.css"
const roboto= Comic_Neue({ subsets: ["latin"],weight:'700' });


export const metadata = {
  title: "Weather APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <Header/>
        </header>
        <CityBar/>
        
        {children}

        </body>
    </html>
  );
}
